apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: v1a3fbbs3-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/v1a3fbbs3-java-quarkus-gitops